### ISSUE TITLE
error when runing pyglet_demo2.py

### ISSUE THREAD

**Issue by dongxinshuai** [greenmoss/PyWavefront#18] opened 2017-11-01 08:13 UTC
I can run ./example/pyglet_demo.py successfully.But when run ./example/pyglet_demo2.py, there is an error in line 15: "meshes = Wavefront('earth.obj')". 

Full information:
```
Traceback (most recent call last):
  File "pyglet_demo2.py", line 15, in <module>
    meshes = Wavefront('earth.obj')
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pywavefront/__init__.py", line 53, in __init__
    ObjParser(self, self.file_name)
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pywavefront/__init__.py", line 75, in __init__
    self.read_file(file_name)
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pywavefront/parser.py", line 44, in read_file
    self.parse(line, dir=os.path.dirname(file_name))
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pywavefront/parser.py", line 67, in parse
    parse_function(args)
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pywavefront/__init__.py", line 89, in parse_mtllib
    materials = material.MaterialParser(mtllib).materials
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pywavefront/material.py", line 118, in __init__
    self.read_file(file_path)
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pywavefront/parser.py", line 44, in read_file
    self.parse(line, dir=os.path.dirname(file_name))
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pywavefront/parser.py", line 67, in parse
    parse_function(args)
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pywavefront/material.py", line 147, in parse_map_Kd
    self.this_material.set_texture(Kd)
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pywavefront/material.py", line 84, in set_texture
    self.texture = texture.Texture(path)
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pywavefront/texture.py", line 41, in __init__
    self.image = pyglet.image.load(self.image_name).texture
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pyglet/image/__init__.py", line 388, in <lambda>
    texture = property(lambda self: self.get_texture(),
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pyglet/image/__init__.py", line 818, in get_texture
    force_rectangle)
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pyglet/image/__init__.py", line 803, in create_texture
    rectangle, force_rectangle)
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pyglet/image/__init__.py", line 1514, in create
    blank)
  File "/home/dxs/anaconda2/envs/dxs_anaconda_env/lib/python2.7/site-packages/pyglet/gl/lib.py", line 104, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: invalid value
```

Thank you  very much!

**Comment by frlnx** [comment] 2017-11-26 19:21
Got the same error importing my own object files. The Ns value in the material file was too high. Had to manually change it

**Comment by henriksod** [comment] 2018-04-23 18:30
I have the same error with my own script (works on linux, not on windows). The Ns value in my MTL file is 0, so... What is the cause then?

**Comment by greenmoss** [comment] 2018-04-25 01:12
The `read` is not handling Unicode properly. Looks like there's an easy solution:

https://github.com/mozilla/unicode-slugify/issues/16#issuecomment-102840930

**Comment by einarf** [comment] 2018-06-09 11:39
I'm pretty sure this issue is already fixed. It's a crash when `Material.set_texture` is called. This no longer triggers texture loading.

**Comment by greenmoss** [comment] 2018-06-09 15:37
Thanks @einarf!

Closing

**Closed by greenmoss** 2018-06-09 15:37 UTC
